### ISSUE TITLE
Flex Daemonset do NOT run a POD on ICP masters (because ICP uses tolerations "key: dedicated" for masters)

### ISSUE THREAD

**Issue by shay-berman** [IBM/ubiquity-k8s#130]
ICP uses tolerations "key: dedicated" annotation rather then "key: node-role.kubernetes.io/master".
So on ICP installation the ubiqutiy flex daemonset was not scheduled flex POD on the masters.
To fix that we should add the "key: dedicated" to the flex daemonset to support both vanilla k8s and ICP
   ```
   tolerations:   
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule  
```
